name: Build the Game and Deploy as GitHub Pages
on: [push]
jobs:
  build-and-deploy:
    name: Build HTML5 & Deploy to Pages
    runs-on: windows-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v2.3.1

      - name: Import HaxeFlixel
        uses: krdlab/setup-haxe@v1
        with:          
          haxe-version: 4.1.5
      - name: Install Libraries
        run: 
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup
          haxelib run lime setup flixel
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install newgrounds
          haxelib install linc_luajit
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib run lime setup windows
      - name: Build HTML5 version
        run: |
          lime build html5

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: export/release/html5 # The folder the action should deploy.